config/routes.rb
TrainingstagebuchExtensions::Application.routes.draw do

  
  resources :users do
    member do
      get 'import_sports'
    end
  end

  resources :sessions , only: [:new, :create, :destroy]

  root :to => 'static_pages#home'

  get "static_pages/home"
  get "static_pages/contact"
  get "static_pages/about"
  get "static_pages/help"

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/contact', to: 'static_pages#contact'
  match '/about',   to: 'static_pages#about'
  match '/help',    to: 'static_pages#help'

  resources :ttb_sessions, only: [:new, :create, :destroy]
  match '/import', to: 'ttb_sessions#new'

  

end

app/controllers/ttb_sessions_controller.rb
class TtbSessionsController < ApplicationController

  # GET
  def new
    render 'new'
  end

  # POST
  def create
    store_ttb_password(params[:ttb_password])
    redirect_to import_sports_user_path(current_user), notice: "OK, got your ttb password."
  end

  private

  

end

app/helpers/ttb_sessions_helper.rb
module TtbSessionsHelper

		# TODO Add error checking
		# TODO Nobody should be able to inject!
    def store_ttb_password(ttb_password)
    	session[:ttb_password] = ttb_password
  	end

  	# TODO Add error checking
  	def retrieve_ttb_password
    	session[:ttb_password]
  	end

end

app/views/ttb_sessions/new.html.erb
<% provide(:title, "New ttbsession") %> 
<h1>TTB/NEW.HTML.ERB</h1>

<div class="row">
  <div class="span6 offset3">
  	<%= form_tag ttb_sessions_path do %>
		<%= label_tag :ttb_password %>
  		<%= password_field_tag :ttb_password %>
  		<%= submit_tag "New ttb session", :class => "btn btn-large btn-primary" %>
  	<% end %>
  </div>
</div>